package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=migrate, returns=null, data={uri=str, *blk=bool, *inc=bool, *detach=bool, *resume=bool}}</pre>
 */
// QApiCommandDescriptor{name=migrate, returns=null, data={uri=str, *blk=bool, *inc=bool, *detach=bool, *resume=bool}}
public class MigrateCommand extends QApiCommand<MigrateCommand.Arguments, MigrateCommand.Response> {
	/** Compound arguments to a MigrateCommand. */
	@JsonInclude(JsonInclude.Include.NON_EMPTY)
	public static class Arguments {

		@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
		@JsonProperty("uri")
		@Nonnull
		public java.lang.String uri;
		@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
		@JsonProperty("blk")
		@CheckForNull
		public java.lang.Boolean blk;
		@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
		@JsonProperty("inc")
		@CheckForNull
		public java.lang.Boolean inc;
		@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
		@JsonProperty("detach")
		@CheckForNull
		public java.lang.Boolean detach;
		@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
		@JsonProperty("resume")
		@CheckForNull
		public java.lang.Boolean resume;

		public Arguments() {
		}

		public Arguments(java.lang.String uri, java.lang.Boolean blk, java.lang.Boolean inc, java.lang.Boolean detach, java.lang.Boolean resume) {
			this.uri = uri;
			this.blk = blk;
			this.inc = inc;
			this.detach = detach;
			this.resume = resume;
		}
	}

	/** Response to a MigrateCommand. */
	public static class Response extends QApiResponse<java.lang.Void> {
	}

	/** Constructs a new MigrateCommand. */
	public MigrateCommand(@Nonnull MigrateCommand.Arguments argument) {
		super("migrate", Response.class, argument);
	}

	/** Constructs a new MigrateCommand. */
	public MigrateCommand(java.lang.String uri, java.lang.Boolean blk, java.lang.Boolean inc, java.lang.Boolean detach, java.lang.Boolean resume) {
		this(new Arguments(uri, blk, inc, detach, resume));
	}
}
