package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=migrate-pause, returns=null, data=null}</pre>
 */
// QApiCommandDescriptor{name=migrate-pause, returns=null, data=null}
public class MigratePauseCommand extends QApiCommand<java.lang.Void, MigratePauseCommand.Response> {

	/** Response to a MigratePauseCommand. */
	public static class Response extends QApiResponse<java.lang.Void> {
	}

	/** Constructs a new MigratePauseCommand. */
	public MigratePauseCommand() {
		super("migrate-pause", Response.class, null);
	}

}
