package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=migrate-recover, returns=null, data={uri=str}}</pre>
 */
// QApiCommandDescriptor{name=migrate-recover, returns=null, data={uri=str}}
public class MigrateRecoverCommand extends QApiCommand<MigrateRecoverCommand.Arguments, MigrateRecoverCommand.Response> {
	/** Compound arguments to a MigrateRecoverCommand. */
	@JsonInclude(JsonInclude.Include.NON_EMPTY)
	public static class Arguments {

		@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
		@JsonProperty("uri")
		@Nonnull
		public java.lang.String uri;

		public Arguments() {
		}

		public Arguments(java.lang.String uri) {
			this.uri = uri;
		}
	}

	/** Response to a MigrateRecoverCommand. */
	public static class Response extends QApiResponse<java.lang.Void> {
	}

	/** Constructs a new MigrateRecoverCommand. */
	public MigrateRecoverCommand(@Nonnull MigrateRecoverCommand.Arguments argument) {
		super("migrate-recover", Response.class, argument);
	}

	/** Constructs a new MigrateRecoverCommand. */
	public MigrateRecoverCommand(java.lang.String uri) {
		this(new Arguments(uri));
	}
}
